services:
  identitydb:
    user: "10001"
    container_name: indentitydb
    build: ./DB/
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
    volumes:
      - identityDb.data:/var/opt/mssql/data
      - identityDb.log:/var/opt/mssql/log
      - identityDb.secrets:/var/opt/mssql/secrets
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "A&VeryComplex123Password" -Q "SELECT 1"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  indentity:
    container_name: indentity
    build:
      context: .
      dockerfile: /IdentityService/Dockerfile
    env_file:
      - ./Environment/security.env
    volumes:
      - security:/security/keys
      - security:/app/Certs
    ports:
      - "5238:8080"
    depends_on:
      identitydb:
        condition: service_healthy

  # library:
  #   container_name: library
  #   build: ./LibraryService/
  #   env_file:
  #     - ./Security/identity.env
  #     - ./Security/security.env
  #   volumes:
  #     - ./Security/Keys:/security/keys
  #   ports:
  #     - "5280:8080"
  #   depends_on:
  #     - librarydb

  # librarydb:
  #   user: "10001"
  #   container_name: librarydb
  #   build: ./DB/
  #   ports:
  #     - "1435:1433"
  #   environment:
  #     - ACCEPT_EULA=y
  #     - SA_PASSWORD=A&VeryComplex123Password
  #   volumes:
  #     - ./sql/library/data:/var/opt/mssql/data
  #     - ./sql/library/log:/var/opt/mssql/log
  #     - ./sql/library/secrets:/var/opt/mssql/secrets

volumes:
  security:
  identityDb.data:
  identityDb.log:
  identityDb.secrets:
