services:
  indentity:
    container_name: indentity
    build: ./IdentityService/
    env_file:
      - ./Security/identity.env
      - ./Security/security.env
    volumes:
      - ./Security/Keys:/security/keys
    ports:
      - "5238:8080"
    depends_on:
      - identitydb

  identitydb:
    user: "10001"
    container_name: indentitydb
    build: ./DB/
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
    volumes:
      - ./sql/identity/data:/var/opt/mssql/data
      - ./sql/identity/log:/var/opt/mssql/log
      - ./sql/identity/secrets:/var/opt/mssql/secrets

  library:
    container_name: library
    build: ./LibraryService/
    env_file:
      - ./Security/identity.env
      - ./Security/security.env
    volumes:
      - ./Security/Keys:/security/keys
    ports:
      - "5280:8080"
    depends_on:
      - librarydb

  librarydb:
    user: "10001"
    container_name: librarydb
    build: ./DB/
    ports:
      - "1435:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
    volumes:
      - ./sql/library/data:/var/opt/mssql/data
      - ./sql/library/log:/var/opt/mssql/log
      - ./sql/library/secrets:/var/opt/mssql/secrets
