// <auto-generated />
using System;
using Library.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.Infrastructure.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Library.Domain.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(62)
                        .HasColumnType("nvarchar(62)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4dc4b580-7fb5-4c2a-938a-7e464116c7dd"),
                            Country = "Russia",
                            DateOfBirth = new DateOnly(1828, 9, 9),
                            FirstName = "Lev",
                            LastName = "Tolstoy"
                        },
                        new
                        {
                            Id = new Guid("21cb29da-047a-4d85-a581-8ef6cffec67f"),
                            Country = "Russia",
                            DateOfBirth = new DateOnly(1868, 3, 28),
                            FirstName = "Maxim",
                            LastName = "Gorkiy"
                        },
                        new
                        {
                            Id = new Guid("3bc8f089-2d00-4346-af71-d9f9fcdceb20"),
                            Country = "Japan",
                            DateOfBirth = new DateOnly(1995, 7, 3),
                            FirstName = "Miya",
                            LastName = "Kazuki"
                        },
                        new
                        {
                            Id = new Guid("188ec0f1-b4a1-4a86-9bb4-f249c2a1032b"),
                            Country = "Russia",
                            DateOfBirth = new DateOnly(1821, 11, 11),
                            FirstName = "Fedor",
                            LastName = "Dostoyevskiy"
                        },
                        new
                        {
                            Id = new Guid("ec891ac2-f620-415f-9f86-3d15259eb071"),
                            Country = "Russia",
                            DateOfBirth = new DateOnly(1809, 1, 4),
                            FirstName = "Nikolay",
                            LastName = "Gogol"
                        },
                        new
                        {
                            Id = new Guid("4792ce31-a3e8-4df3-b0d7-4ea1c8e40dbd"),
                            Country = "United Kingdom",
                            DateOfBirth = new DateOnly(1564, 4, 23),
                            FirstName = "William",
                            LastName = "Shakespeare"
                        },
                        new
                        {
                            Id = new Guid("ac31fda2-411c-4669-8e42-b4b18cc659cb"),
                            Country = "Belarus",
                            DateOfBirth = new DateOnly(1924, 6, 22),
                            FirstName = "Vasil",
                            LastName = "Bykov"
                        });
                });

            modelBuilder.Entity("Library.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("BorrowTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurrentReaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Genre")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ReaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CurrentReaderId");

                    b.HasIndex("ReaderId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14ca202e-dfb4-4d97-b7ef-76cf510bf319"),
                            AuthorId = new Guid("4dc4b580-7fb5-4c2a-938a-7e464116c7dd"),
                            AuthorName = "Lev Tolstoy",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc varius rhoncus nisl, nec egestas lacus pellentesque vitae. Donec eleifend urna at nunc tincidunt facilisis. Nam consectetur odio erat sed.",
                            Genre = "Novel",
                            ISBN = "ISBN 13: 9781566190275",
                            IsAvailable = true,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = new Guid("2f346383-bd6a-4564-8dce-343c355e795a"),
                            AuthorId = new Guid("4dc4b580-7fb5-4c2a-938a-7e464116c7dd"),
                            AuthorName = "Lev Tolstoy",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc varius rhoncus nisl, nec egestas lacus pellentesque vitae. Donec eleifend urna at nunc tincidunt facilisis. Nam consectetur odio erat sed.",
                            Genre = "Novel",
                            ISBN = "ISBN 13: 9780672523830",
                            IsAvailable = true,
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            Id = new Guid("ad9c4dbe-5dff-43e0-a58c-cea9327a4464"),
                            AuthorId = new Guid("21cb29da-047a-4d85-a581-8ef6cffec67f"),
                            AuthorName = "Maxim Gorkiy",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc varius rhoncus nisl, nec egestas lacus pellentesque vitae. Donec eleifend urna at nunc tincidunt facilisis. Nam consectetur odio erat sed.",
                            Genre = "Friction",
                            ISBN = "ISBN-13: 9798390533352",
                            IsAvailable = true,
                            Title = "Old Izergil"
                        },
                        new
                        {
                            Id = new Guid("f31001c4-fb5d-42f0-aafd-dd0e6e08476e"),
                            AuthorId = new Guid("3bc8f089-2d00-4346-af71-d9f9fcdceb20"),
                            AuthorName = "Miya Kazuki",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc varius rhoncus nisl, nec egestas lacus pellentesque vitae. Donec eleifend urna at nunc tincidunt facilisis. Nam consectetur odio erat sed.",
                            Genre = "Friction",
                            ISBN = "ISBN-13: 9781718357976",
                            IsAvailable = true,
                            Title = "Ascendance of a bookworm"
                        },
                        new
                        {
                            Id = new Guid("6328fcf9-5846-4f7c-960c-da5ea5c32f22"),
                            AuthorId = new Guid("188ec0f1-b4a1-4a86-9bb4-f249c2a1032b"),
                            AuthorName = "Fedor Dostoyevskiy",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc varius rhoncus nisl, nec egestas lacus pellentesque vitae. Donec eleifend urna at nunc tincidunt facilisis. Nam consectetur odio erat sed.",
                            Genre = "Novel",
                            ISBN = "ISBN 13: 9785050000149",
                            IsAvailable = true,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = new Guid("424e64e8-c811-42ef-8153-f7952ced8c51"),
                            AuthorId = new Guid("188ec0f1-b4a1-4a86-9bb4-f249c2a1032b"),
                            AuthorName = "Fedor Dostoyevskiy",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc varius rhoncus nisl, nec egestas lacus pellentesque vitae. Donec eleifend urna at nunc tincidunt facilisis. Nam consectetur odio erat sed.",
                            Genre = "Novel",
                            ISBN = "ISBN 10: 0374528373",
                            IsAvailable = true,
                            Title = "The Brothers Karamazov"
                        },
                        new
                        {
                            Id = new Guid("81ebde25-7b81-4bf2-8691-edef624642d8"),
                            AuthorId = new Guid("ec891ac2-f620-415f-9f86-3d15259eb071"),
                            AuthorName = "Nikolay Gogol",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc varius rhoncus nisl, nec egestas lacus pellentesque vitae. Donec eleifend urna at nunc tincidunt facilisis. Nam consectetur odio erat sed.",
                            Genre = "Satire",
                            ISBN = "ISBN 10: 0300060998",
                            IsAvailable = true,
                            Title = "Dead souls"
                        },
                        new
                        {
                            Id = new Guid("8e32b21e-1a32-4272-bc46-6f7b709a7696"),
                            AuthorId = new Guid("4792ce31-a3e8-4df3-b0d7-4ea1c8e40dbd"),
                            AuthorName = "William Shakespeare",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc varius rhoncus nisl, nec egestas lacus pellentesque vitae. Donec eleifend urna at nunc tincidunt facilisis. Nam consectetur odio erat sed.",
                            Genre = "Shakespearean tragedy",
                            ISBN = "ISBN 13: 9780671722852",
                            IsAvailable = true,
                            Title = "Romeo and Juliet"
                        },
                        new
                        {
                            Id = new Guid("a0283873-60b8-45de-a411-02a0a3fbc465"),
                            AuthorId = new Guid("ac31fda2-411c-4669-8e42-b4b18cc659cb"),
                            AuthorName = "Vasil Bykov",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc varius rhoncus nisl, nec egestas lacus pellentesque vitae. Donec eleifend urna at nunc tincidunt facilisis. Nam consectetur odio erat sed.",
                            Genre = "War novel",
                            ISBN = "ISBN 13: 9781909156821",
                            IsAvailable = true,
                            Title = "Alpine Ballad"
                        });
                });

            modelBuilder.Entity("Library.Domain.Entities.Reader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("Library.Domain.Entities.Book", b =>
                {
                    b.HasOne("Library.Domain.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Domain.Entities.Reader", "CurrentReader")
                        .WithMany()
                        .HasForeignKey("CurrentReaderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Library.Domain.Entities.Reader", null)
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("ReaderId");

                    b.Navigation("Author");

                    b.Navigation("CurrentReader");
                });

            modelBuilder.Entity("Library.Domain.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Library.Domain.Entities.Reader", b =>
                {
                    b.Navigation("BorrowedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
